### ISSUE TITLE
Invalid JSON issue

### ISSUE THREAD

**Issue by dadlex** [ansible-dellemc-unity/dellemc-unity-sdk#4]
For now runner.py breaks when it tries to retrieve the JSON created by AnsibleModule on any YAML playbook.
runner.py, line 25:
`module = AnsibleModule(argument_spec=arguments, supports_check_mode=True)`

Error message:
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed"}

**Comment by l0ki000** [comment]
the key is to have
```
ANSIBLE_METADATA = {'metadata_version': '0.1',
                    'status': ['unstableinterface'],
                    'supported_by': 'students'}
from ansible.module_utils.basic import AnsibleModule
```
in module file, even if you are not using/calling ```AnsibleModule```
seems that by this import core ansible interpreting it as ANSIBALLZMODULE, not as old and unsupported JSON module.
